### PR TITLE
Clean-up the test array builder.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
See each commit for more details. This fixes some failures around passing encryption keys.

### CODE REVIEW

**Comment by ihnorton** [comment]
It's a bit tricky to compare arrays directly (we really need a format-aware compare tool), but if I do a comparison of one of the encrypted subdirectory variations, I see a lot of differences where I _think_ the content should be deterministic -- can you please check why?:
```
Binary files arrays/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1679751034458_1679751034458_80ef33ae3de84aa6bcf34f104b4fe0ae_18/a9_validity.tdb and ../v2_15_0/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1678849548628_1678849548628_2210e1095e2c46fa8e28ccf63411c8a3_18/a9_validity.tdb differ
Binary files arrays/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1679751034458_1679751034458_80ef33ae3de84aa6bcf34f104b4fe0ae_18/a9_var.tdb and ../v2_15_0/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1678849548628_1678849548628_2210e1095e2c46fa8e28ccf63411c8a3_18/a9_var.tdb differ
Binary files arrays/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1679751034458_1679751034458_80ef33ae3de84aa6bcf34f104b4fe0ae_18/d0.tdb and ../v2_15_0/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1678849548628_1678849548628_2210e1095e2c46fa8e28ccf63411c8a3_18/d0.tdb differ
Binary files arrays/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1679751034458_1679751034458_80ef33ae3de84aa6bcf34f104b4fe0ae_18/d1.tdb and ../v2_15_0/v2_15_0/SPARSE_v2_15_0_UINT64_DATETIME_US_encryption_AES_256_GCM/__fragments/__1678849548628_1678849548628_2210e1095e2c46fa8e28ccf63411c8a3_18/d1.tdb differ
```

**Comment by ihnorton** [comment]
Hmm, it could also be due to 9ceab2fb523

**Comment by teo-tsirpanis** [comment]
AES-GCM encryption uses a unique nonce. If only encrypted arrays show differences this is expected.

**Comment by ihnorton** [comment]
I see, thanks - however, the non-encrypted arrays are also different:
```
pydev ❯ diff -r ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1678849405961_1678849405961_276be155b7a44ac49279e97bf5912296_18/ arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1679750904195_1679750904195_32a8fb7792304400be2e291b8174f9b6_18/
Binary files ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1678849405961_1678849405961_276be155b7a44ac49279e97bf5912296_18/__fragment_metadata.tdb and arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1679750904195_1679750904195_32a8fb7792304400be2e291b8174f9b6_18/__fragment_metadata.tdb differ

```

**Comment by ihnorton** [comment]
I see, thanks - however, the non-encrypted arrays are also different:
```
pydev ❯ diff -r ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1678849405961_1678849405961_276be155b7a44ac49279e97bf5912296_18/ arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1679750904195_1679750904195_32a8fb7792304400be2e291b8174f9b6_18/
Binary files ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1678849405961_1678849405961_276be155b7a44ac49279e97bf5912296_18/__fragment_metadata.tdb and arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1679750904195_1679750904195_32a8fb7792304400be2e291b8174f9b6_18/__fragment_metadata.tdb differ

```

**Comment by ihnorton** [comment]
Ok looking through with @dhoke4tdb, it seems like the only difference for the non-encrypted arrays is in the fragment metadata -- which makes sense:
```
pydev ❯ diff -r ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/** arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/**                 ✘ 1
Binary files ../v2_15_0/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1678849405961_1678849405961_276be155b7a44ac49279e97bf5912296_18/__fragment_metadata.tdb and arrays_teo/v2_15_0/DENSE_v2_15_0_DATETIME_YEAR/__fragments/__1679750904195_1679750904195_32a8fb7792304400be2e291b8174f9b6_18/__fragment_metadata.tdb differ

```

**Review by ihnorton — APPROVED** [review]

**Pull request merged**
